<?php

namespace app\yiis\web;

use Yii;

class Application extends \yii\web\Application
{
    public function init()
    {
        $this->_request = parent::getRequest();
        $this->_response = parent::getResponse();
        $this->_session = parent::getSession();
        parent::init();
    }

    protected function bootstrap()
    {
        Yii::setAlias('@webroot', APP_PATH . '/web');
        Yii::setAlias('@web', '/');
        \yii\base\Application::bootstrap();
    }

    public function coreComponents()
    {
        return array_merge(parent::coreComponents(), [
            'request' => ['class' => Request::class],
            'response' => ['class' => Response::class],
            'session' => ['class' => 'yii\web\Session'],
            'errorHandler' => ['class' => 'yii\web\ErrorHandler'],
        ]);
    }

    private $_request;

    public function getRequest()
    {
        return $this->_request;
    }


    private $_response;

    public function getResponse()
    {
        return $this->_response;
    }

    private $_session;

    public function getSession()
    {
        return $this->_session;
    }

    // @TODO 重写为连接池
    public function getDb()
    {
        return parent::getDb(); // TODO: Change the autogenerated stub
    }
}