<?php

namespace app\yiis\web;

class Application extends \yii\web\Application
{
    public function coreComponents()
    {
        return array_merge(parent::coreComponents(), [
            'request' => ['class' => Request::class],
            'response' => ['class' => Response::class],
            'session' => ['class' => 'yii\web\Session'],
            'errorHandler' => ['class' => 'yii\web\ErrorHandler'],
        ]);
    }

    private $_request;

    public function getRequest()
    {
        return $this->_request;
    }

    public function setRequest(array $config)
    {
        \Yii::$container->clear($config['class']);
        $this->_request = \Yii::createObject($config);
    }

    private $_response;

    public function getResponse()
    {
        return $this->_response;
    }

    public function setResponse(array $config)
    {
        \Yii::$container->clear($config['class']);
        $this->_response = \Yii::createObject($config);
    }

    private $_session;

    public function getSession()
    {
        return $this->_session;
    }

    public function setSession(array $config)
    {
        \Yii::$container->clear($config['class']);
        $this->_session = \Yii::createObject($config);
    }

    // @TODO 重写为连接池
    public function getDb()
    {
        return parent::getDb(); // TODO: Change the autogenerated stub
    }
}