<?php

namespace app\yiis\web;

class Application extends \yii\web\Application
{
    public function coreComponents()
    {
        return parent::coreComponents(); // TODO: Change the autogenerated stub
    }
}